DROP DATABASE IF EXISTS todolist;
CREATE DATABASE todolist;

\c  todolist;

CREATE TABLE IF NOT EXISTS todo (
    todo_id INT GENERATED ALWAYS AS IDENTITY,
    item TEXT NOT NULL,
    priority INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (todo_id)
);

CREATE TABLE IF NOT EXISTS completed (
    completed_id INT GENERATED ALWAYS AS IDENTITY,
    item TEXT NOT NULL,
    PRIMARY KEY (completed_id)
);